# Generated by Django 5.1.1 on 2024-11-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='actor_pics/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='producer_pics/'),
        ),
    ]
